# Configuration file for go command line utility

# The name of the directory with dictionary files
DictionaryDir: data/dictionary

# The names of the lexical unit files
LUFiles: cnotes_zh_en_dict.tsv,fgs_mwe.txt,translation_memory_buddhist.txt,translation_memory_literary.txt,buddhist_terminology.txt,buddhist_named_entities.txt,translation_memory_hsingyun.txt

# Location that the templates are found
TemplateDir: html/material-templates

# The domain of the corpus
Domain: Buddhism

# Domains to list translations for in the Contained in section of headword pages
ContainsByDomain: Buddhism

# Sub-domains to avoid
AvoidSubDomains: Physics,Paleontology

# Web site title
Title: NTI Reader

NotesReMatch: "(T ([0-9]))(\)|,|;)","(T ([0-9]{2}))(\)|,|;)","(T ([0-9]{3}))(\)|,|;)","(T ([0-9]{4}))(\)|,|;)"
NotesReplace: "<a class='regular' href='/taisho/t000${2}.html'>${1}</a>${3}","<a class='regular' href='/taisho/t00${2}.html'>${1}</a>${3}","<a class='regular' href='/taisho/t0${2}.html'>${1}</a>${3}","<a class='regular' href='/taisho/t${2}.html'>${1}</a>${3}"
