# Configuration file for go command line utility

# The name of the directory with dictionary files
DictionaryDir: data/dictionary

# The names of the lexical unit files
LUFiles: words.txt,fgs_mwe.txt,translation_memory_buddhist.txt,translation_memory_literary.txt,buddhist_named_entities.txt

# The domain of the corpus
Domain: Buddhism

# Domains to list translations for in the Contained in section of headword pages
ContainsByDomain: Buddhism

# Sub-domains to avoid
AvoidSubDomains: Physics,Paleontology
