# Configuration file for go command line utility

# The name of the directory with dictionary files
DictionaryDir: data/dictionary

# The names of the lexical unit files
LUFiles: words.txt,fgs_mwe.txt,translation_memory_buddhist.txt

# The domain of the corpus
Domain: Buddhism