# Configuration file for web application

# Extract terms from notes field into reverse index
NotesExtractorPattern: "Sanskrit equivalent: (.*?)[\(,\,,\;]","Pali: (.*?)[\(,\,,\;]"

# IndexCorpus is the name of the corpus for the term frequency index in Firestore.
IndexCorpus: ntireader

 # IndexGen is the generation number for the term frequency index in Firestore.
IndexGen: 0

# gets whether to add a directory prefix to collection names in full text search
AddDirectoryToCol: True