apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ntireader-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ntireader-app
  template:
    metadata:
      labels:
        run: ntireader-app
    spec:
      containers:
      - name: ntireader-app
        image: gcr.io/hbreader-162018/cn-app-image:r97
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "20m"
        env:
          - name: SITEDOMAIN
            value: ntireader.org
          - name: PORT
            value: "8081"
          - name: DBHOST
            value: 127.0.0.1
          - name: DATABASE
            value: ntireader
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DBPASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
          - name: AVG_DOC_LEN
            value: "6376"
          - name: TEXT_BUCKET
            value: "ntinreader-text"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
        ports:
        - containerPort: 8081
          protocol: TCP
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=hbreader-162018:us-central1:cnotes=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
         - name: cloudsql-instance-credentials
           mountPath: /secrets/cloudsql
           readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: google-cloud-key
        secret:
          secretName: cnotes-app-key                    